### ISSUE TITLE
Screenshots in Description and Website

### ISSUE THREAD

**Issue by lambdaupb** [jacquetc/skribisto#10]
I know it is in alpha stage, but it would be really useful to have some screenshots on the website.

Compiling or at least downloading the app first is too much effort to get a glance at the UI.

Thanks for your cool project.

**Comment by jacquetc** [comment]
Hello, 

I'll add some screenshots when the C++ library I'm writing is finished. There aren't much to see right now, since what I'm working on is "under the hood". Howerever, thank you for reminding me to post an update on the project's website :-)

Cordialement,
Cyril Jacquet, lead Plume Creator developer

**Comment by CodingInSecret** [comment]
Yes, I'd love to see photos or an update on the progress as well.
