### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by EugeneUvin** [jacquetc/skribisto#104]
I am wondering if Skribisto interface has any translation files that can be edited to add interface languages? I can help with translating into:
* Russian, and 
* Ukrainian 

languages.

**Comment by jacquetc** [comment]
Well, not right now, but since you are asking, I'll add the language codes so the files will appear. You will be able to fetch them in src/translations (the .ts files) and use Qt Linguist to translate. Thank you for wanting to help me :-)

As Skribisto isn't finished, please keep in mind that there will be changes in the future. Translations files will be updated automatically to reflect these changes, you will only have to translate the new words.

**Comment by EugeneUvin** [comment]
Created two separate issues for this

https://github.com/jacquetc/skribisto/issues/105
https://github.com/jacquetc/skribisto/issues/106
