### ISSUE TITLE
Can't associate characters to scene.

### ISSUE THREAD

**Issue by arielzao150** [jacquetc/skribisto#13]
I can fully create the characters, but I can't associate them to any scene. I click and drag them to the scene's attendance on top of the list of characters and a block sign appears on the mouse.

**Comment by jacquetc** [comment]
Hello arielzao150, can you tell me on which OS you are ? I wish to try and reproduce the problem.

**Comment by arielvm150** [comment]
It's Ubuntu 16.04 (I'm not sure about the version, but it's the latest LTS) and a clean install. I wanted to have a machine just for writing and installed Ubuntu alongside Windows 10, so basically all I have on the Ubuntu is Plume Creator and a sort of pernsonal Wiki to organize the novel I'm writing. That's all.
If there's anything else you would need, I am willing to help. I also know a bit of programming, but I'm always learning more because I studying Computer Engineering at college (going to 5th semester so I'm not too deep in it yet). I loved this project and all it's ideas, so I would like to help in any way I can.
Cheers,
Ariel Vitor Molina. Friday, 12 January 2018, 05:01PM -02:00 from Cyril Jacquet  notifications@github.com :
