### ISSUE TITLE
Crashing when opening file

### ISSUE THREAD

**Issue by wilemrbj** [jacquetc/skribisto#17]
On debian Stretch, plume-creator is version 0.66+dfsg1-3.1+b2 when I'm trying to open a *.plume file made on another computer running the same version, but on Ubuntu 16+ (can't get the version now), Plume (already opened) crashes. In the terminal I get "Exception en point flottant." ("Floating point exception" I guess in english...

I can still open the *.plume file on Ubuntu.
The size of the file is 189 822 o

**Comment by jacquetc** [comment]
Maybe it is an incompatibility with newer Qt libraries ? The last version is 0.67

**Comment by abergmot** [comment]
I will try with the 0.67 version but it was working well on debian stretch until then, with the same project, and I didn't upgrade anything. 
The only change is that the file grew a little bigger.

**Comment by abergmot** [comment]
I already tried to unzip my *.plume file to see if I had still access to the texts and found those in the text directory as .html files, so I was not worried anymore that the file was corrupt.
I don't believe the problem comes from different version because I have been using this same file on the 2 different computers for months  with no problems. So nothing changed except the growing size really and suddenly it didn't work only on Debian (which wasn't upgraded). 
I'll try 0.67 when I have some time.

**Comment by jacquetc** [comment]
Strange, please keep me updated. Next version will have a SQLite database file replacing the zip, so this sort of incident will (hopefully) disappear.
